#ifndef MINTBOOT_MB_VIRT_MMIO_H
#define MINTBOOT_MB_VIRT_MMIO_H

#include <stdint.h>

#define VIRT_GF_TTY_MMIO_BASE  0xff008000u
#define VIRT_GF_CTRL_MMIO_BASE 0xff009000u
#define VIRT_GF_RTC_MMIO_BASE  0xff006000u
#define VIRT_GF_PIC_MMIO_BASE  0xff000000u
#define VIRT_GF_PIC_STRIDE     0x00001000u
#define VIRT_VIRTIO_MMIO_BASE  0xff010000u
#define VIRT_VIRTIO_MMIO_STRIDE 0x00000200u
#define VIRT_VIRTIO_MMIO_SLOTS 32u

#define GOLDFISH_TTY_PUT_CHAR      0x00
#define GOLDFISH_TTY_BYTES_READY   0x04
#define GOLDFISH_TTY_CMD           0x08
#define GOLDFISH_TTY_DATA_PTR      0x10
#define GOLDFISH_TTY_DATA_LEN      0x14
#define GOLDFISH_TTY_DATA_PTR_HIGH 0x18

#define GOLDFISH_CMD_INT_ENABLE    0x01
#define GOLDFISH_CMD_WRITE_BUFFER  0x02
#define GOLDFISH_CMD_READ_BUFFER   0x03

#define GOLDFISH_CTRL_REG_CMD      0x04
#define GOLDFISH_CTRL_CMD_HALT     0x02
#define GOLDFISH_CTRL_CMD_PANIC    0x03

#define GOLDFISH_PIC_STATUS        0x00
#define GOLDFISH_PIC_NUMBER        0x04
#define GOLDFISH_PIC_DISABLE_ALL   0x08
#define GOLDFISH_PIC_DISABLE       0x0c
#define GOLDFISH_PIC_ENABLE        0x10

#define GOLDFISH_RTC_TIME_LOW      0x00
#define GOLDFISH_RTC_TIME_HIGH     0x04
#define GOLDFISH_RTC_ALARM_LOW     0x08
#define GOLDFISH_RTC_ALARM_HIGH    0x0c
#define GOLDFISH_RTC_IRQ_ENABLED   0x10
#define GOLDFISH_RTC_CLEAR_ALARM   0x14
#define GOLDFISH_RTC_ALARM_STATUS  0x18
#define GOLDFISH_RTC_CLEAR_INTERRUPT 0x1c

#define VIRTIO_MMIO_MAGIC_VALUE         0x000
#define VIRTIO_MMIO_VERSION             0x004
#define VIRTIO_MMIO_DEVICE_ID           0x008
#define VIRTIO_MMIO_DEVICE_FEATURES     0x010
#define VIRTIO_MMIO_DEVICE_FEATURES_SEL 0x014
#define VIRTIO_MMIO_DRIVER_FEATURES     0x020
#define VIRTIO_MMIO_DRIVER_FEATURES_SEL 0x024
#define VIRTIO_MMIO_QUEUE_SEL           0x030
#define VIRTIO_MMIO_QUEUE_NUM_MAX       0x034
#define VIRTIO_MMIO_QUEUE_NUM           0x038
#define VIRTIO_MMIO_QUEUE_READY         0x044
#define VIRTIO_MMIO_QUEUE_NOTIFY        0x050
#define VIRTIO_MMIO_INTERRUPT_STATUS    0x060
#define VIRTIO_MMIO_INTERRUPT_ACK       0x064
#define VIRTIO_MMIO_STATUS              0x070
#define VIRTIO_MMIO_QUEUE_DESC_LOW      0x080
#define VIRTIO_MMIO_QUEUE_DESC_HIGH     0x084
#define VIRTIO_MMIO_QUEUE_AVAIL_LOW     0x090
#define VIRTIO_MMIO_QUEUE_AVAIL_HIGH    0x094
#define VIRTIO_MMIO_QUEUE_USED_LOW      0x0a0
#define VIRTIO_MMIO_QUEUE_USED_HIGH     0x0a4
#define VIRTIO_MMIO_CONFIG              0x100

#define VIRTIO_STATUS_ACKNOWLEDGE 1u
#define VIRTIO_STATUS_DRIVER      2u
#define VIRTIO_STATUS_DRIVER_OK   4u
#define VIRTIO_STATUS_FEATURES_OK 8u

#define VIRTIO_ID_BLOCK 2u

#define VIRTIO_BLK_T_IN  0u
#define VIRTIO_BLK_T_OUT 1u

#define VIRTQ_DESC_F_NEXT  1u
#define VIRTQ_DESC_F_WRITE 2u

static inline void mb_mmio_write32(uintptr_t addr, uint32_t value)
{
	*(volatile uint32_t *)addr = value;
}

static inline uint32_t mb_mmio_read32(uintptr_t addr)
{
	return *(volatile uint32_t *)addr;
}

#endif /* MINTBOOT_MB_VIRT_MMIO_H */
